### ISSUE TITLE
Answer Key

### ISSUE THREAD

**Issue by Yedrej** [kosukeimai/qss-swirl#8]
I cannot find an answer key to the exercises provided, both the numerical answers to the questions and the code. Is this available?

**Comment by kosukeimai** [comment]
The answers are given in `yaml` files.

**Comment by Yedrej** [comment]
The answers for the final exercises of the chapters are not in the yaml files. I am looking for the answers to each exercise at the end of the chapters. I also cannot find some of the data sets throughout the chapter, for example, "congress.csv" in chapter 3: Measurement.

For example, the exercises at the end of chapter 3. There is neither the data set nor an answer key for this.
![image](https://user-images.githubusercontent.com/124520763/217557093-7ffe8cc2-2f97-4d3a-9e56-6c6680f6b3ca.png)

Are these available anywhere?

**Comment by kosukeimai** [comment]
Exercise solutions are only available for instructors through the Princeton University Press website.
